// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB_PiKqt4kkoO8-Ps2iKtMhYvu5knMXUM',
    appId: '1:1074095996867:web:375b619be18b3f094a4776',
    messagingSenderId: '1074095996867',
    projectId: 'fir-ricardopiedra',
    authDomain: 'fir-ricardopiedra.firebaseapp.com',
    storageBucket: 'fir-ricardopiedra.appspot.com',
    measurementId: 'G-GBZVZQZ7Y8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDck7oqLwmnYCL1aNa_IBBbvc8GFMvXvh4',
    appId: '1:1074095996867:android:ca7e19c85a47e8e34a4776',
    messagingSenderId: '1074095996867',
    projectId: 'fir-ricardopiedra',
    storageBucket: 'fir-ricardopiedra.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo_UP4m2Q-XyG8tow6uX0_7N48kAaGq3U',
    appId: '1:1074095996867:ios:4be2466b193841454a4776',
    messagingSenderId: '1074095996867',
    projectId: 'fir-ricardopiedra',
    storageBucket: 'fir-ricardopiedra.appspot.com',
    iosClientId: '1074095996867-njupifpb9ldsltqc13rldb6reocq8t4v.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectoRicardopiedra',
  );
}
